_format_version: "2.1"
_transform: true

services:
  # Service d'authentification
  - name: auth-service
    url: http://auth-service:3000
    routes:
      - name: auth-routes
        paths:
          - /api/auth
        strip_path: true
    plugins:
      - name: cors
      - name: prometheus
      - name: rate-limiting
        config:
          minute: 20
          hour: 200
          policy: local

  # Service IA/Chat
  - name: ai-service
    url: http://ai-service:5000
    routes:
      - name: chat-routes
        paths:
          - /api/chat
        strip_path: true
    plugins:
      - name: cors
      - name: prometheus
      - name: rate-limiting
        config:
          minute: 10
          hour: 100
          policy: local

  # Service d'intégration AWS
  - name: aws-integration-service
    url: http://aws-integration-service:4000
    routes:
      - name: aws-integration-routes
        paths:
          - /api/integrations/aws
        strip_path: true
    plugins:
      - name: cors
      - name: prometheus
      - name: rate-limiting
        config:
          minute: 30
          hour: 300
          policy: local

  # Service d'intégration Datadog
  - name: datadog-integration-service
    url: http://datadog-integration-service:4001
    routes:
      - name: datadog-integration-routes
        paths:
          - /api/integrations/datadog
        strip_path: true
    plugins:
      - name: cors
      - name: prometheus
      - name: rate-limiting
        config:
          minute: 30
          hour: 300
          policy: local

  # Service d'intégration OVH
  - name: ovh-integration-service
    url: http://ovh-integration-service:4002
    routes:
      - name: ovh-integration-routes
        paths:
          - /api/integrations/ovh
        strip_path: true
    plugins:
      - name: cors
      - name: prometheus
      - name: rate-limiting
        config:
          minute: 30
          hour: 300
          policy: local

  # Service de stockage
  - name: storage-service
    url: http://storage-service:6000
    routes:
      - name: data-routes
        paths:
          - /api/data
        strip_path: true
    plugins:
      - name: cors
      - name: prometheus
      - name: rate-limiting
        config:
          minute: 30
          hour: 300
          policy: local

  # Route pour la documentation des API
  - name: docs-service
    url: http://docs-service:8080
    routes:
      - name: docs-routes
        paths:
          - /api/docs
        strip_path: true
    plugins:
      - name: cors

  # Route pour vérifier la santé du système
  - name: health-service
    url: http://health-service:8081
    routes:
      - name: health-routes
        paths:
          - /api/health
        strip_path: false

# Plugins globaux appliqués à toutes les routes
plugins:
  - name: cors
    config:
      origins:
        - https://app.athena.example.com
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Content-Type
        - Authorization
      credentials: true
      preflight_continue: false
      max_age: 3600

  - name: rate-limiting
    config:
      minute: 60
      hour: 1000
      policy: local

  - name: prometheus
    config: {}

  - name: request-termination
    config:
      status_code: 404
      message: "Route not found"
    routes:
      - name: catch-all
        paths:
          - /api/not-implemented 